### ISSUE TITLE
(Linux) emulator doesn't start with Wayland

### ISSUE THREAD

**Issue by SpelzR2** [jsgroth/jgenesis#143]
jgenesis doesn't start & work with KDE Wayland. Even though it should work with Xwayland, which runs in the background. Terminal output when starting the emulator:

`xkbcommon: ERROR: /usr/share/X11/locale/en_US.UTF-8/Compose:1661:1: unrecognized keysym "dead_hamza" on left-hand side
xkbcommon: ERROR: /usr/share/X11/locale/en_US.UTF-8/Compose:1662:1: unrecognized keysym "dead_hamza" on left-hand side
xkbcommon: ERROR: /usr/share/X11/locale/en_US.UTF-8/Compose:1663:1: unrecognized keysym "dead_hamza" on left-hand side
xkbcommon: ERROR: /usr/share/X11/locale/en_US.UTF-8/Compose:1664:1: unrecognized keysym "dead_hamza" on left-hand side
xkbcommon: ERROR: /usr/share/X11/locale/en_US.UTF-8/Compose:1665:1: unrecognized keysym "dead_hamza" on left-hand side
[2024-12-20T20:09:09Z ERROR eframe::native::run] Exiting because of error: Found no glutin configs matching the template: ConfigTemplate { color_buffer_type: Rgb { r_size: 8, g_size: 8, b_size: 8 }, alpha_size: 8, depth_size: 0, stencil_size: 0, num_samples: None, min_swap_interval: None, max_swap_interval: None, config_surface_types: ConfigSurfaceTypes(WINDOW), api: None, transparency: false, single_buffering: false, stereoscopy: None, float_pixels: false, max_pbuffer_width: None, hardware_accelerated: None, max_pbuffer_height: None, native_window: None }. Error: provided display handle is not supported
Error: NoGlutinConfigs(ConfigTemplate { color_buffer_type: Rgb { r_size: 8, g_size: 8, b_size: 8 }, alpha_size: 8, depth_size: 0, stencil_size: 0, num_samples: None, min_swap_interval: None, max_swap_interval: None, config_surface_types: ConfigSurfaceTypes(WINDOW), api: None, transparency: false, single_buffering: false, stereoscopy: None, float_pixels: false, max_pbuffer_width: None, hardware_accelerated: None, max_pbuffer_height: None, native_window: None }, Error { raw_code: None, raw_os_message: None, kind: NotSupported("provided display handle is not supported") })
`

**Comment by jsgroth** [comment]
This looks extremely similar to the issue reported in https://github.com/emilk/egui/issues/3174, although the issue itself occurs in a lower-level library.

Testing on the Kubuntu 24.10 live ISO, I get a (different) fatal error if I try to run the release AppImage build, but it seems to work fine if I build from source. It looks like it's trying to use Wayland natively but the AppImage build is missing some required libraries (or has outdated library versions).

As a temporary workaround you can set the environment variable `WAYLAND_DISPLAY=""` when running the AppImage to force it to use XWayland, which seems to work. I'll see if I can either fix the libraries in the AppImage build or just disable native Wayland support (since it clearly doesn't work properly).

**Comment by SpelzR2** [comment]
In the past I've switched manually to X11 to start jgenesis. Using the WAYLAND_DISPLAY="" environment works as intended. The emulator starts. 

However with my PC I'm not able to play a game. Neither Vulkan nor OpenGL API works. 
With Vulkan I encounter this error message:
![jgnesis crash](https://github.com/user-attachments/assets/b659abee-5cb2-437b-9e59-9c39f4056001)

Using OpenGL the logfile shows this:
`[2024-12-21T08:07:30Z INFO  genesis_core::memory] ROM CRC32: 0CAAA4AC
[2024-12-21T08:07:30Z INFO  genesis_core::memory] Genesis hardware region: Americas
[2024-12-21T08:07:30Z INFO  genesis_core::memory] Using Sega banked mapper: false
[2024-12-21T08:07:30Z INFO  genesis_core::api] Using timing / display mode Ntsc
[2024-12-21T08:07:30Z WARN  wgpu_hal::gles::egl] EGL_MESA_platform_surfaceless not available. Using default platform
thread '<unnamed>' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-22.0.0/src/gles/egl.rs:854:88:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace` 

Seems the emulator has trouble to render the surface (screen). I have an AMD card and are using the amdgpu driver (Mesa & Vulkan are up to date). On my old PC with an Nvidia card jgenesis worked (using Debian 12 KDE with X11 on that machine). Seems to be AMD related.

**Comment by jsgroth** [comment]
Hmm, the laptop that I tested with has an AMD iGPU and I was able to launch games after setting `WAYLAND_DISPLAY=""`, with both the Vulkan and OpenGL backends. This problem might be specific to AMD dedicated GPUs, or it might be an issue with certain distros since I only tested in latest Kubuntu. I can test in a few other distros that use KDE Plasma w/ Wayland to see if I can reproduce this.

https://github.com/gfx-rs/wgpu/issues/2762 and https://github.com/gfx-rs/wgpu/issues/3922 seem possibly related - it looks like in some configurations, wgpu will default to Wayland even when rendering to an X11 window, which causes the wgpu instance to fail during initialization. It doesn't look like wgpu provides an easy way to force X11 right now, but there might be another way to fix this (if this is what's happening).

Some additional wgpu logs would be helpful. Could you run the emulator with the environment variable `RUST_LOG=info` set and paste the logs? The emulator suppresses some wgpu logs by default because they're very noisy (particularly with the Vulkan backend), but those logs would be helpful to get a better idea of what's happening here.

**Comment by SpelzR2** [comment]
Is there a specific location where to logfile is store? I can't find the logfile, however when looking through the logs from heroic launcher there is an additional line about wgpu with rust_log=info enabled:
`[2024-12-21T21:59:45Z WARN  wgpu_hal::gles::egl] EGL_MESA_platform_surfaceless not availabe`

I've attache the last lines of the logfile with rust_log=info:
[crash rust_log.txt](https://github.com/user-attachments/files/18220092/crash.rust_log.txt)

**Comment by jsgroth** [comment]
All logs are written to stdout unless the launcher is redirecting them somewhere else. I wouldn't expect the logs to be split between different files, at any rate.

That `EGL_MESA_platform_surfaceless` message seems to indicate that either wgpu is failing to load EGL 1.5+, or it's failing to load both the Wayland and X11 display libraries. Otherwise I would expect to see a wgpu log message like `Using Wayland platform` or `Using X11 platform`.

What output do you get if you run `eglinfo` in a terminal?

That looks like it was with the OpenGL backend - do you get the same log messages with the Vulkan backend?

I'd also be interested to know if the AppImage builds from here work any better. These are the same code as current master, but built on an Ubuntu 24.04 image instead of 22.04 so they include more recent library versions of things like libwayland:
https://github.com/jsgroth/jgenesis/actions/runs/12449295292

I haven't been able to reproduce this exact error yet. I was able to reproduce the error described in https://github.com/gfx-rs/wgpu/issues/3922 when using the OpenGL backend on Linux Mint using Cinnamon w/ Wayland, but setting `WAYLAND_DISPLAY=""` is enough to fix that particular error.

**Comment by SpelzR2** [comment]
eglinfo lists all OpenGL extensions... interestingly I also have spotted two lines at the beginning:
> _amdgpu_device_initialize: amdgpu_query_info(ACCEL_WORKING) failed (-13)
> amdgpu: amdgpu_device_initialize failed.

Maybe the problem lays on my end and something is wrong with my driver? It's strange since everything is up to date (I'm using Solus 4.6) and seems to work fine. To be sure I'll download another Linux Distribution (Kubuntu 24.10) and will make a quick test to see if it reports the same.

Running the newer AppImage with Wayland give me this:
> [2024-12-22T08:54:06Z ERROR eframe::native::run] Exiting because of error: Found no glutin configs matching the template: ConfigTemplate { color_buffer_type: Rgb { r_size: 8, g_size: 8, b_size: 8 }, alpha_size: 8, depth_size: 0, stencil_size: 0, num_samples: None, min_swap_interval: None, max_swap_interval: None, config_surface_types: ConfigSurfaceTypes(WINDOW), api: None, transparency: false, single_buffering: false, stereoscopy: None, float_pixels: false, max_pbuffer_width: None, hardware_accelerated: None, max_pbuffer_height: None, native_window: None }. Error: provided display handle is not supported
Error: NoGlutinConfigs(ConfigTemplate { color_buffer_type: Rgb { r_size: 8, g_size: 8, b_size: 8 }, alpha_size: 8, depth_size: 0, stencil_size: 0, num_samples: None, min_swap_interval: None, max_swap_interval: None, config_surface_types: ConfigSurfaceTypes(WINDOW), api: None, transparency: false, single_buffering: false, stereoscopy: None, float_pixels: false, max_pbuffer_width: None, hardware_accelerated: None, max_pbuffer_height: None, native_window: None }, Error { raw_code: None, raw_os_message: None, kind: NotSupported("provided display handle is not supported") })

**Comment by jsgroth** [comment]
Ok, I'm going to see what I can do to force eframe (the GUI window) to always use X11 even when running in a Wayland environment. The emulator windows are always\* X11 anyway.

It'll probably be a few days before I can test this in Fedora or Solus, but I'll try with those when I get a chance to see if I can reproduce that error from your second post. I unfortunately don't have any AMD dGPUs (at least not any remotely recent ones) so if I can't reproduce then it's going to be hard to figure this out without getting an RX 7600 or something.

\* It's possible to force these to Wayland by setting the environment variable `SDL_VIDEODRIVER=wayland`, but for me this causes the window to display maximized without decorations which is a pretty bad UX. SDL3 probably fixes this, but SDL3 doesn't seem to be stable yet

**Comment by jsgroth** [comment]
I was able to reproduce all of these errors exactly in the latest version of Solus Plasma running on my AMD iGPU laptop, so I will be able to look into this more.

To start with, I tested with a custom AppImage build that doesn't have DEBUG/TRACE logs compiled out like the release builds do. Setting `WAYLAND_DISPLAY=""` (because otherwise the app fails to launch), when I try to launch a game with the Vulkan backend, I get these logs:

```
[2024-12-27T18:54:40Z WARN  wgpu_hal::vulkan::instance] Unable to find extension: VK_KHR_surface
[2024-12-27T18:54:40Z WARN  wgpu_hal::vulkan::instance] Unable to find extension: VK_KHR_xlib_surface
[2024-12-27T18:54:40Z WARN  wgpu_hal::vulkan::instance] Unable to find extension: VK_KHR_xcb_surface
[2024-12-27T18:54:40Z WARN  wgpu_hal::vulkan::instance] Unable to find extension: VK_KHR_wayland_surface
[2024-12-27T18:54:40Z WARN  wgpu_hal::vulkan::instance] Unable to find extension: VK_EXT_swapchain_colorspace
[2024-12-27T18:54:40Z WARN  wgpu_hal::vulkan::instance] Unable to find extension: VK_KHR_get_physical_device_properties2
[2024-12-27T18:54:40Z DEBUG wgpu_core::instance] Instance::new: failed to create Vulkan backend: InstanceError { message: "Entry::create_instance() failed", source: Some(ERROR_INCOMPATIBLE_DRIVER) }
[2024-12-27T18:54:40Z TRACE wgpu_core::instance] Instance::new: backend Gl not requested
[2024-12-27T18:54:40Z TRACE wgpu_core::global] Global::drop
[2024-12-27T18:54:40Z ERROR jgenesis_gui::emuthread] Error initializing emulator: Error creating wgpu surface: Failed to create surface for any enabled backend: {}
```

With the GL backend (not much more than what you pasted earlier):
```
[2024-12-27T18:55:04Z TRACE wgpu_core::instance] Instance::new: backend Vulkan not requested
[2024-12-27T18:55:04Z DEBUG wgpu_hal::gles::egl] Client extensions: []
[2024-12-27T18:55:04Z WARN  wgpu_hal::gles::egl] EGL_MESA_platform_surfaceless not available. Using default platform
thread '<unnamed>' panicked at /home/jsgroth/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-23.0.1/src/gles/egl.rs:899:88:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

In both cases it looks like wgpu is failing to load the relevant graphics libraries for some reason.

Interestingly, if I build from source then the app works fine (with the Vulkan backend), even without setting `WAYLAND_DISPLAY=""`. This makes me think the cause is a bug in how I'm building the AppImage rather than a bug in wgpu. I'm going to experiment with replacing some of the system libraries that are being packaged into the AppImage.

**Comment by jsgroth** [comment]
I think I've figured out how to fix this: exclude all Wayland-related libraries (`libwayland*`) when packaging the AppImage, so that the app exclusively uses OS-provided versions of Wayland libraries. I'm not entirely sure why, but having mismatched versions of Wayland libraries seems to cause wgpu to fail to load _any_ graphics libraries on some platforms, even when using X11 or XWayland.

Excluding Wayland libraries also seems to fix the app failing to start at all in Wayland, so there's no longer a need to run in X11 or set `WAYLAND_DISPLAY=""`. The GUI window will use Wayland directly and the SDL2 emulator window will automatically use XWayland.

The app still crashes if you try to launch a game with the OpenGL backend while running in Wayland (without forcing XWayland), but the Vulkan backend seems to work fine. I'll open a separate issue to note the bug with the OpenGL backend.

I want to do a little more testing before I merge this, but AppImage builds with this fix are available here if you'd like to test:
https://github.com/jsgroth/jgenesis/actions/runs/12519992037

**Comment by SpelzR2** [comment]
I've tested the latest AppImage and can confirm that the emulator now works with Vulkan & Wayland. As you've said OpenGL still crashes the emulator.
